"""Generate the capability table from the runtime registry."""
from pathlib import Path

from fluxctl.capabilities import capability_markdown, filesystem_capabilities


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "capability_registry.md"


def main() -> None:
    lines = [
        "# Capability Registry",
        "",
        "This file is generated by `scripts/generate_capability_docs.py`; edit `src/fluxctl/capabilities.py` instead.",
        "",
        capability_markdown(filesystem_capabilities()),
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
