"""IMD exporter supporting IMD.v1 subset."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import List

from ..models import LayoutDescriptor, Sector, TrackSectors
from ..scp import sha256_file

MODE_MAP = {
    "ibm_mfm_1440k": 0x04,
    "ibm_mfm_1200k": 0x04,
    "ibm_mfm_720k": 0x03,
    "ibm_mfm_360k": 0x03,
}


def _sector_type(sector: Sector, force: bool) -> int:
    if sector.state == "missing":
        return 0x00
    if sector.confidence < 0.5 and not force:
        return 0x00
    if len(set(sector.data)) == 1:
        return 0x02
    return 0x01


def export_imd(track_data: List[TrackSectors], layout: LayoutDescriptor, out_path: Path, provenance: dict, force: bool = False) -> None:
    mode = MODE_MAP.get(layout.layout_id, 0x03)
    header_lines = [
        "Generated by fluxctl",
        f"UTC: {datetime.now(timezone.utc).isoformat()}",
        f"Layout: {layout.layout_id}",
        f"Source SHA256: {provenance.get('input_sha256', '')}",
    ]
    header = "\r\n".join(header_lines) + "\r\n\x1a"
    with out_path.open("wb") as fh:
        fh.write(header.encode("ascii", errors="replace"))
        for ts in sorted(track_data, key=lambda t: (t.track, t.side)):
            sectors_sorted = sorted(ts.sectors, key=lambda s: s.sector_id)
            fh.write(bytes([mode, ts.track, ts.side, len(sectors_sorted), 0x02]))
            fh.write(bytes([s.sector_id for s in sectors_sorted]))
            for sector in sectors_sorted:
                stype = _sector_type(sector, force=force)
                fh.write(bytes([stype]))
                if stype == 0x01:
                    fh.write(sector.data)
                elif stype == 0x02:
                    fill = sector.data[:1] if sector.data else b"\x00"
                    fh.write(fill)
    provenance.update(
        {
            "output_sha256": sha256_file(out_path),
            "layout_id": layout.layout_id,
            "mode": mode,
        }
    )
    out_path.with_suffix(out_path.suffix + ".provenance.json").write_text(json.dumps(provenance, indent=2), encoding="utf-8")
